---
    AWSTemplateFormatVersion: 2010-09-09
    Description: 'Network Redux CloudFormation -  Aurora MySQL Cluster Stack'
    Parameters:
        Environment:
            Description: demo Environment
            Type: 'AWS::SSM::Parameter::Value<String>'
            Default: '/build/environment/demo'
        Client:
            Description: Client Name
            Type: 'AWS::SSM::Parameter::Value<String>'
            Default: '/demo/client' 
        DatabaseInstanceType:
            Default: db.t3.medium
            Type: String
        AvailabiltyZone1:
            Description: Set Availability Zone 1
            Type: 'AWS::SSM::Parameter::Value<String>'
            Default: '/demo/AvailabiltyZone1'
        AvailabiltyZone2:
            Description: Set Availability Zone 2
            Type: 'AWS::SSM::Parameter::Value<String>'
            Default: '/demo/AvailabiltyZone2'
        DatabasePassword:
            AllowedPattern: "[a-zA-Z0-9]+"
            ConstraintDescription: must contain only alphanumeric characters.
            Description: The database admin account password.
            MaxLength: '41'
            MinLength: '20'
            NoEcho: 'true'
            Type: String
        DatabaseUsername:
            AllowedPattern: "[a-zA-Z0-9]+"
            ConstraintDescription: must contain only alphanumeric characters.
            Description: The database admin account user name.
            MaxLength: '16'
            MinLength: '1'
            Type: String
        DatabaseBackupRetentionPeriod:
            Type: String
            Default: 15
            AllowedValues:
                - 1
                - 7
                - 10
                - 15
                - 30
            Description: The database backup retention period in days.
        DatabaseSubnets:
            Description: The subnets to place database instances in.
            Type: List<AWS::EC2::Subnet::Id>
        DatabaseSecurityGroups:
            Type: List<AWS::EC2::SecurityGroup::Id>
            Description: Security groups to apply to the RDS cluster.
    Metadata:
        AWS::CloudFormation::Interface:
            ParameterGroups:
                - Label:
                    default: Database Configuration
                  Parameters:
                    - DatabaseInstanceType
                    - DatabaseName
                    - DatabaseUsername
                    - DatabasePassword
                    - DatabaseSubnets
                    - DatabaseSecurityGroups
                    - DatabaseBackupRetentionPeriod
            ParameterLabels:
                DatabaseInstanceType:
                    default: Database Instance Type
                DatabasePassword:
                    default: Database Password
                DatabaseUsername:
                    default: Database Username
                DatabaseBackupRetentionPeriod:
                    default: Database Backup Retention Period
                DatabaseSubnets:
                    default: Database Subnets
                DatabaseSecurityGroups:
                    default: Database Security Groups
    Resources:
        DatabaseSubnetGroup:
          Type: AWS::RDS::DBSubnetGroup
          Properties:
            DBSubnetGroupDescription: demo RDS subnet group
            SubnetIds:
              - Fn::ImportValue:
                   Fn::Sub: 'subnet-${Environment}-${Client}-rds-private-${AWS::Region}-az1'
              - Fn::ImportValue:
                   Fn::Sub: 'subnet-${Environment}-${Client}-rds-private-${AWS::Region}-az2'
        RDSParamGroup:
            Type: AWS::RDS::DBParameterGroup
            Properties:
               Family: aurora-mysql5.7
               Description: Database Parameter Group
               Tags:
                - Key: Name 
                  Value:  !Sub 'paramgroup-${Environment}-${Client}-mysql5.7'
        RDSClusterParamGroup:
           Type: AWS::RDS::DBClusterParameterGroup
           Properties:
              Family: aurora-mysql5.7
              Description: Database Parameter Group
              Parameters : {
               time_zone : "UTC"
              }
              Tags:
              - Key: Name 
                Value: !Sub 'clusterparamgroup-${Environment}-${Client}-mysql5.7'
            
        DatabaseCluster:
            Type: AWS::RDS::DBCluster
            Properties:
                DBClusterIdentifier: !Sub 'db-cluster-${Environment}-${Client}'
                Engine: aurora-mysql
                StorageEncrypted: true
                MasterUsername:
                    Ref: 'DatabaseUsername'
                MasterUserPassword:
                    Ref: 'DatabasePassword'
                BackupRetentionPeriod:
                    Ref: DatabaseBackupRetentionPeriod
                PreferredBackupWindow: 02:00-03:00
                PreferredMaintenanceWindow: sun:03:00-sun:04:00
                DBSubnetGroupName:
                    Ref: DatabaseSubnetGroup
                VpcSecurityGroupIds:
                    Ref: DatabaseSecurityGroups
                DBClusterParameterGroupName:
                    Ref : RDSClusterParamGroup
        DatabasePrimaryInstance001:
            Type: AWS::RDS::DBInstance
            Properties:
                Engine: aurora-mysql
                StorageEncrypted: true
                DBClusterIdentifier:
                    Ref: DatabaseCluster
                DBInstanceClass:
                    Ref: DatabaseInstanceType
                DBSubnetGroupName:
                    Ref: DatabaseSubnetGroup
                DBParameterGroupName:
                    Ref: RDSParamGroup 
                DBInstanceIdentifier: !Sub 'db-${Environment}-${Client}' 