---
AWSTemplateFormatVersion: 2010-09-09
Description: Demo  - IAM Stack - Creates WebRole

Parameters:
  Client:
    Description: Client Name
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/demo/client'  

Resources:

  CreateTagRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${Client}-createtag-role-policy'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - ec2:DescribeTags
              - ec2:CreateTags
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:DescribeLogGroups
              - logs:CreateLogStream
              - logs:CreateLogGroup             
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:PutParameter
            Resource: arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*
      Roles:
        - !Ref 'WebRole'
  WebRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'iam-${Client}-web-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM'
  WebInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Sub 'iam-${Client}-web-profile'
      Path: /
      Roles:
        - Ref: WebRole
